version: "3"

services: 
    mongodb:
        image: mongo
        container_name: "mongo-db"
        ports:
            - "27017:27017"
            - "27018:27018"
            - "27019:27019"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
        volumes: 
            - "db:/var/lib/mongodb"
            - "db-backup:/var/lib/backup"

    songure-api:
        build: './songure-api'
        container_name: "songure-api"
        ports:
            - "8080:8080"
       
volumes: 
    db: {}
    db-backup: {}